// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'login_model.g.dart';

@JsonSerializable()
class LoginModel {
  final String login;
  final String password;

  LoginModel({
    required this.login,
    required this.password,
  });
}
